#!/bin/bash
#
# Perform necessary sensu removal steps
# after package is uninstalled.
#


sensu_services="sensu-client sensu-service" # sensu-server sensu-api sensu-dashboard"

# Disable and stop sensu services
for service in $sensu_services; do
	chkconfig $service off
	chkconfig --del $service
	if [ -e "/etc/init.d/$service" ]; then
	    /etc/init.d/$service stop || true
	    rm -f /etc/init.d/$service
	fi
done

# unlink logroate config
[ -e /etc/logrotate.d/sensu ] && rm -f /etc/logrotate.d/sensu

# Delete sensu files
if [ -d "/opt/contegix/sensu" ]; then
	rm -rf /opt/contegix/sensu
fi

# Delete sensu user
if getent passwd sensu >/dev/null; then
	userdel -f sensu
fi

# Delete sensu group
if getent group sensu >/dev/null; then
	groupdel -f sensu
fi

exit 0
