#!/bin/bash

# chkconfig: 345 90 90
# description: Sensu monitoring framework api

### BEGIN INIT INFO
# Provides:       sensu-api
# Required-Start: $remote_fs $network
# Required-Stop:  $remote_fs $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Sensu monitoring framework api
### END INIT INFO

prefix="contegix-"
/etc/init.d/${prefix}sensu-service api $1

exit $?
