#!/bin/bash
#
# Perform necessary sensu removal steps
# before package is uninstalled.
#

prefix="blacklight-"
install_dir="/opt/blacklight/sensu"
sensu_services="sensu-client sensu-service" # sensu-server sensu-api sensu-dashboard"

# upgrade

# uninstall
if [ "${1}" -eq "0" ] ; then

	# Disable and stop sensu services
	for service in $sensu_services; do
		service="${prefix}${service}"
		if [ -h /etc/init.d/${service} ] ; then
			chkconfig ${service} off
			chkconfig --del ${service}
			/etc/init.d/${service} status 2>&1 > /dev/null && /etc/init.d/${service} stop
			rm -f /etc/init.d/${service}
		fi
	done

	# unlink logroate config
	[ -e /etc/logrotate.d/${prefix}sensu ] && rm -f /etc/logrotate.d/${prefix}sensu

fi 

exit 0
