#!/bin/bash
#
# Perform necessary sensu removal steps
# after package is uninstalled.
#

prefix="contegix-"
install_dir="/opt/contegix/sensu"

# Delete sensu user
if getent passwd ${prefix}sensu >/dev/null; then
	userdel -f ${prefix}sensu
fi

# Delete sensu group
if getent group ${prefix}sensu >/dev/null; then
	groupdel -f ${prefix}sensu
fi

exit 0
